#!/bin/sh

#pacman -S sudo

#Essentials

#sudo pacman -S git openssh base-devel neovim zsh xorg

read -p "Insert username: " username

#Default username to "gala"

[ -z "$username" ] && username="gala"

#sudo useradd -m -g wheel $username
#sudo passwd $username

#Give user permissions

#sudo sed -i 's/#%wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers

#Change to user

su $username

#Pull dotfiles and personal repos

# git clone https://github.com/gtLara/dot.git
# git clone https://github.com/gtLara/ssh.git 
# git clone https://github.com/gtLara/dwm-bar.git

#Install stuff
#Pacman

pacman=(
imagemagick
mpv
dunst
sxiv
)

sudo pacman -S ${pacman[*]}

#Yay

#git clone https://aur.archlinux.org/yay.git ; cd yay ; makepkg -si ; cd ~

yay=(
spotify-tui
)

yay -S ${yay[*]}

#Git
#TODO: Git Install Funcs
#TODO: Resolver root/user yay install issue (find way to change user and install)
