#!/bin/sh

#pacman -S sudo

#Essentials

#sudo pacman -S git openssh base-devel neovim zsh xorg

read -p "Insert username: " username

#Default username to "gala"

[ -z "$username" ] && username="gala"

#sudo useradd -m -g wheel $username
#sudo passwd $username

#Give user permissions

#sudo sed -i 's/#%wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' /etc/sudoers

#Execute profileboot

#runuser -c "sh profileboot" $username
