#!/bin/sh

function suckless(){
    git clone $repo
    dir=$(echo $repo | cut -d'/' -f5)
    cd $dir
    sudo make install
    cd ~
}

cd ~

read -p "Confirm that SSH is setup. Press any key to continue" trash

#Pull dotfiles and personal repos

git clone git@github.com:gtLara/dot.git
git clone git@github.com:gtLara/dwm-bar.git

#Install stuff
Pacman

pacman=(
wget
imagemagick
mpv
alsa-utils
dunst
sxiv
unclutter
zathura
zathura-pdf-poppler # zathura pdf extension
chromium # for brave
bluez #todo: get bluetooth right lol
bluez-utils
pulseaudio
pulseaudio-bluetooth
realtime-privileges # supercollider stuff
jack2
cadence
zip # compression stuff
unzip
unrar
)

sudo pacman -S ${pacman[*]}

git clone https://aur.archlinux.org/yay.git ; cd yay ; makepkg -si; cd ~

yay=(
sxhkd # simple x hotkey daemon
brave
ntfs-3g # for seagate mount
)

yay -S ${yay[*]}

# Suckless

builds="https://github.com/LukeSmithxyz/"

for r in "st" "dwm" "dmenu"; do repo=$builds$r; suckless; done

 mkdir .suckless
 mv st dwm dmenu dwm-bar .suckless

# Conda

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh;

# Vim Plug

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Zsh stuff

# setting shared history file

mkdir -p ~/.cache/zsh
touch -p ~/.cache/zsh/zhist

# setting plugs

sudo mkdir -p /usr/share/zsh/plugins
mkdir temp
cd temp
git clone git@github.com:zsh-users/zsh-history-substring-search.git
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git
git clone git@github.com:zsh-users/zsh-autosuggestions.git

sudo mv zsh-history-substring-search /usr/share/zsh/plugins
sudo mv zsh-syntax-highlighting /usr/share/zsh/plugins
sudo mv zsh-autosuggestions /usr/share/zsh/plugins

cd ../
rm -rf temp
